package batch

import (
	"bufio"
	"encoding/json"
	"fmt"
	"log"
	"strings"

	"google.golang.org/genai"
)

// RequestItem represents a single prompt request item to be serialized.
type RequestItem struct {
	CustomID string
	Prompt   string
}

// ResponseItem represents the parsed result mapped back to the custom ID.
type ResponseItem struct {
	CustomID string
	Text     string
	Error    string
}

// BatchRequest matches the request payload structure of Vertex AI Batch API.
type BatchRequest struct {
	CustomID string            `json:"customId"`
	Request  *RequestContainer `json:"request"`
}

// RequestContainer contains the content payload.
type RequestContainer struct {
	Contents []*genai.Content `json:"contents"`
}

// BatchResponse matches the output response structure of Vertex AI Batch API.
type BatchResponse struct {
	CustomID string             `json:"customId"`
	Response *ResponseContainer `json:"response"`
	Error    *ResponseError     `json:"error,omitempty"`
}

// ResponseContainer contains the candidates generated by the model.
type ResponseContainer struct {
	Candidates []*genai.Candidate `json:"candidates"`
}

// ResponseError represents an error returned by the Vertex AI Batch API for a request.
type ResponseError struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// GenerateRequestsJSONL serializes multiple RequestItems into a single JSONL string.
func GenerateRequestsJSONL(items []RequestItem) (string, error) {
	var sb strings.Builder
	for _, item := range items {
		req := BatchRequest{
			CustomID: item.CustomID,
			Request: &RequestContainer{
				Contents: []*genai.Content{
					genai.NewContentFromText(item.Prompt, "user"),
				},
			},
		}
		bytes, err := json.Marshal(req)
		if err != nil {
			return "", fmt.Errorf("failed to marshal request for custom ID %s: %w", item.CustomID, err)
		}
		sb.Write(bytes)
		sb.WriteByte('\n')
	}
	return sb.String(), nil
}

// ParseResponsesJSONL parses a JSONL string containing BatchResponse records.
func ParseResponsesJSONL(jsonlContent string) ([]ResponseItem, error) {
	var results []ResponseItem
	scanner := bufio.NewScanner(strings.NewReader(jsonlContent))
	// Configure scanner buffer to support lines up to 10MB
	buf := make([]byte, 0, 64*1024)
	scanner.Buffer(buf, 10*1024*1024)

	var scannedNonEmptyLines int
	var failedUnmarshalCount int

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		scannedNonEmptyLines++

		// Sanitize null bytes to prevent JSON unmarshalling errors
		line = strings.ReplaceAll(line, "\x00", "")

		var resp BatchResponse
		if err := json.Unmarshal([]byte(line), &resp); err != nil {
			log.Printf("Warning: failed to unmarshal response line: %v", err)
			failedUnmarshalCount++
			continue
		}

		item := ResponseItem{
			CustomID: resp.CustomID,
		}

		if resp.Error != nil {
			item.Error = fmt.Sprintf("API error code %d: %s", resp.Error.Code, resp.Error.Message)
		} else if resp.Response != nil && len(resp.Response.Candidates) > 0 {
			cand := resp.Response.Candidates[0]
			if cand != nil && cand.Content != nil && len(cand.Content.Parts) > 0 && cand.Content.Parts[0] != nil {
				item.Text = cand.Content.Parts[0].Text
			}
		}

		results = append(results, item)
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("error reading response JSONL: %w", err)
	}


	if scannedNonEmptyLines > 0 && failedUnmarshalCount == scannedNonEmptyLines {
		return nil, fmt.Errorf("failed to parse any valid lines from JSONL (all %d lines failed to unmarshal)", scannedNonEmptyLines)
	}

	return results, nil
}
